# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('E', 'e-mail'), ('P', 'telefone')], max_length=1, verbose_name='tipo'),
        ),
    ]
