# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
        migrations.AlterModelOptions(
            name='courseold',
            options={'verbose_name': 'mini-curso', 'verbose_name_plural': 'mini-cursos'},
        ),
    ]
